# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: è‚æ˜ç…§çš„åšå®¢
subtitle: æ¡ƒæä¸è¨€ï¼Œä¸‹è‡ªæˆè¹Š
description: éšç¬”ã€æ—¥å¿—ã€æŠ€æœ¯åˆ†äº«ã€ä¸ªäººä½œå“
keywords: è‚æ˜ç…§, åšå®¢, Hexo
author: è‚æ˜ç…§
language: zh-CN
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://www.niemingzhao.top
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: default
theme_config:
  theme_color:
    primary: brown
    accent: blue

  notice: ã€ğŸ’–æ¬¢è¿æ¥åˆ°æœ¬ç«™ï¼Œå¦‚æœå–œæ¬¢å°±ç•™ä¸ªè¨€å§ğŸ’–ã€‘

  favicon: /images/favicon.jpg
  banner: /images/banner.jpg
  avatar: /images/avatar.jpg
  rss: /atom.xml

  email: 1432440963@qq.com
  sns:
    twitter:
    facebook:
    google_plus:
    weibo: https://weibo.com/2360828682/profile
    instagram:
    tumblr:
    github: https://github.com/niemingzhao
    linkedin:
    zhihu: https://www.zhihu.com/people/nie-1-58
    douban:
    qq: tencent://message/?uin=1432440963&Menu=yes
    wechat:

  open_graph:
    twitter:
    google_plus:
    fb_admins:
    fb_app_id:
  site_verification:
    google: fXjtlIfaDc_X-0P11rO3bEp1Nk4IKXphoJv0GqGZCco
    baidu: I3t1wfwZvd
  analytics:
    google_site_id: UA-139531378-1
    baidu_site_id: 22e4d3b73c21ec2f0e1b4f3ff78c9a9c
    cnzz_site_id:

  pages:
    - name: æ—¶é—´è½´
      link: /timeline
    - name: æ ‡ç­¾äº‘
      link: /tagcloud
    - name: ç›¸å†Œ
      link: /gallery
    - name: ç”µè§†ç›´æ’­
      link: /tv
  links:
    - name: hao123
      link: //www.hao123.com

  since: 2016
  footer_text: ' | Theme - <a href="https://github.com/niemingzhao/niemingzhao.github.io/tree/theme" target="_blank" class="mdui-text-color-theme-accent">default</a><br><img src="https://www.beian.gov.cn/img/new/gongan.png">äº¬å…¬ç½‘å®‰å¤‡ <a href="https://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11010502053272" target="_blank" class="mdui-text-color-theme-accent">11010502053272</a>å· | äº¬ICPå¤‡<a href="https://beian.miit.gov.cn" target="_blank" class="mdui-text-color-theme-accent">2023020255</a>å·-1'
  license: æœ¬æ–‡éµå¾ª <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh" target="_blank">CC BY-NC-SA 4.0</a> è®¸å¯åè®®

  gallery:
    fancybox_css: //cdn.bootcdn.net/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css
    fancybox_js: //cdn.bootcdn.net/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js
    jquery_js: //cdn.bootcdn.net/ajax/libs/jquery/3.3.1/jquery.min.js
    lazyload_js: //cdn.bootcdn.net/ajax/libs/jquery_lazyload/1.9.7/jquery.lazyload.min.js
  busuanzi:
    site: true
    page: true
    busuanzi_js: //busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
  qrcode:
    caption: å‘é€åˆ°æ‰‹æœº
    use: plugin
  donate:
    - name: æ”¯ä»˜å®
      link: /images/alipay.jpg
    - name: å¾®ä¿¡æ”¯ä»˜
      link: /images/wechat.jpg
  search:
    placeholder: è¯·è¾“å…¥å…³é”®å­—
    path: /search.xml
    use: plugin
  comment:
    use: gitalk
    disqus_shortname:
    gitalk_client_id: c3d07683889a30cce9f4
    gitalk_client_secret: 4075822d529574759bcaf8f1b55618cf6f1421f9
    gitalk_repo: niemingzhao.github.io
    gitalk_owner: niemingzhao
    gitalk_sid_type: uuid
    livere_data_uid:
    valine_leancloud_app_id:
    valine_leancloud_app_key:
    valine_placeholder:
    valine_page_size:
    valine_avatar:
    valine_lang:
    valine_guest_info:
    valine_notify:
    valine_verify:
    valine_sid_type:
    changyan_app_id:
    changyan_app_key:
    changyan_sid_type:

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  - type: git
    repo: git@github.com:niemingzhao/niemingzhao.github.io.git
    branch: master

# Markdown
## Docs: https://github.com/niemingzhao/hexo-renderer-markdown#readme
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    langPrefix: language-
    linkify: true
    typographer: true
    quotes: â€œâ€â€˜â€™
  plugins:
    markdown-it-anchor:
      level: 1
      permalink: true
      slugify: function (s){return encodeURIComponent(String(s).trim().toLowerCase().replace(/\s+/g,"-"))}
      tabIndex: -1
      uniqueSlugStartIndex: 1
      renderPermalink: function (b,c,d,a){var f;var e=[Object.assign(new d.Token("link_open","a",1),{attrs:[["class",c.permalinkClass],["href",c.permalinkHref(b,d)],["aria-hidden",true]]}),new d.Token("link_close","a",-1)];(f=d.tokens[a+1].children)["push"].apply(f,e)}
      permalinkClass: header-anchor
      permalinkSpace: false
      permalinkSymbol: ""
      permalinkBefore: false
    markdown-it-attrs:
      leftDelimiter: "{"
      rightDelimiter: "}"
      allowedAttributes: []
    markdown-it-checkbox:
      divWrap: false
      divClass: checkbox
      idPrefix: checkbox
    markdown-it-texmath:
      katexCssSrc: //cdn.jsdelivr.net/npm/katex/dist/katex.min.css
      texmathCssSrc: //cdn.jsdelivr.net/npm/markdown-it-texmath/css/texmath.min.css
      texmathDelimiters: dollars
      throwOnError: false
      errorColor: "#cc0000"
      macros: { "\\RR": "\\mathbb{R}" }

# Restful
## Docs: https://github.com/yscoder/hexo-generator-restful#readme
restful:
  # site å¯é…ç½®ä¸ºæ•°ç»„é€‰æ‹©æ€§ç”ŸæˆæŸäº›å±æ€§
  # site: ['title', 'subtitle', 'description', 'author', 'since', email', 'favicon', 'avatar']
  site: true # hexo.config mix theme.config
  posts_size: 10 # æ–‡ç« åˆ—è¡¨åˆ†é¡µï¼Œ0 è¡¨ç¤ºä¸åˆ†é¡µ
  posts_props: # æ–‡ç« åˆ—è¡¨é¡¹çš„éœ€è¦ç”Ÿæˆçš„å±æ€§
    title: true
    slug: true
    date: true
    updated: true
    comments: true
    path: true
    excerpt: false
    cover: true # å°é¢å›¾ï¼Œå–æ–‡ç« ç¬¬ä¸€å¼ å›¾ç‰‡
    content: false
    keywords: false
    categories: true
    tags: true
  categories: true # åˆ†ç±»æ•°æ®
  use_category_slug: false # Use slug for filename of category data
  tags: true # æ ‡ç­¾æ•°æ®
  use_tag_slug: false # Use slug for filename of tag data
  post: true # æ–‡ç« æ•°æ®
  pages: false # é¢å¤–çš„ Hexo é¡µé¢æ•°æ®, å¦‚ About
