theme_color:
  primary: indigo
  accent: pink

notice:

favicon: /images/favicon.png
banner: /images/banner.png
avatar: /images/avatar.png
rss: /atom.xml

email:
sns:
  twitter:
  facebook:
  google_plus:
  weibo:
  instagram:
  tumblr:
  github:
  linkedin:
  zhihu:
  douban:
  qq:
  wechat:

open_graph:
  twitter:
  google_plus:
  fb_admins:
  fb_app_id:
site_verification:
  google:
  baidu:
analytics:
  google_site_id:
  baidu_site_id:
  cnzz_site_id:

pages:
- name: 时间轴
  link: /timeline
- name: 标签云
  link: /tagcloud
- name: 相册
  link: /gallery
links:

since:
footer_text:
license:

gallery:
  fancybox_css: //cdn.bootcdn.net/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css
  fancybox_js: //cdn.bootcdn.net/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js
  jquery_js: //cdn.bootcdn.net/ajax/libs/jquery/3.3.1/jquery.min.js
  lazyload_js: //cdn.bootcdn.net/ajax/libs/jquery_lazyload/1.9.7/jquery.lazyload.min.js
busuanzi:
  site: false
  page: false
  busuanzi_js: //busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
qrcode:
  caption: 发送到手机
  use: online
donate:
search:
  placeholder: 请输入关键字
  path: /search.xml
  use: online
comment:
  use: false
  disqus_shortname:
  gitalk_client_id:
  gitalk_client_secret:
  gitalk_repo:
  gitalk_owner:
  gitalk_sid_type:
  livere_data_uid:
  valine_leancloud_app_id:
  valine_leancloud_app_key:
  valine_placeholder:
  valine_page_size:
  valine_avatar:
  valine_lang:
  valine_guest_info:
  valine_notify:
  valine_verify:
  valine_sid_type:
  changyan_app_id:
  changyan_app_key:
  changyan_sid_type:
